# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    dotnet tool restore
  displayName: 'Install prereq'

- script: |
    echo "$BUILD_VERSION $FEED_PAT"
    dotnet fake build --target packageandpush
    
  env:
    BUILD_VERSION : $(Build.BuildNumber)
    FEED_PAT: $(FEED_PAT)
  displayName: 'release'