# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  Major: '1'
  Minor: '2'
  Patch: '$(Rev:r)'
  
steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.0.x'
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'restore'    

- script: |
    dotnet tool restore
    dotnet paket update
  displayName: 'Install prereq'

- task: NuGetCommand@2
  displayName: "Pack nuget"
  inputs:
    command: pack
    packagesToPack: 'src/*.fsproj'
    majorVersion: '$Major'
    minorVersion: '$Minor'
    patchVersion: '$Patch'
    
- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'
- task: NuGetCommand@2
  displayName: "Push nuget"
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '45c29cd0-03bf-4f63-ac71-3c366095dda9/2447d53d-0348-4176-b5f4-4c55ed2d94c3'
    allowPackageConflicts: true
