# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  BUILD_VERSION: '$(Build.BuildId)'
  
steps:
- task: UseDotNet@2
  displayName: "Use net5"
  inputs:
    packageType: 'sdk'
    version: '5.0.x'
- task: DotNetCoreCLI@2
  displayName: "Resoter tools"
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'restore'    

- script: dotnet paket update
  displayName: 'install packages'

- task: DotNetCoreCLI@2
  displayName: "Pack the package"
  inputs:
    command: 'pack'
    packagesToPack: '**/*.fsproj'
    versioningScheme: 'off'

- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'
- task: DotNetCoreCLI@2
  displayName: "Push the package"
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '45c29cd0-03bf-4f63-ac71-3c366095dda9/2447d53d-0348-4176-b5f4-4c55ed2d94c3'